/*
-- FISH_TYPE 별 가장 큰 길이
SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
GROUP BY FISH_TYPE
*/

/*
-- ID, FISH_TYPE, LENGTH 반환 (해당 테이블의 FISH_TYPE과 FISH_NAME_INFO 테이블의 FISH_TYPE으로 조인)
SELECT ID, A.FISH_TYPE, A.LENGTH FROM FISH_INFO A 
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
      GROUP BY FISH_TYPE) B ON (A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH)
*/

SELECT B.ID, A.FISH_NAME, B.LENGTH FROM FISH_NAME_INFO A
JOIN (SELECT ID, A.FISH_TYPE, A.LENGTH FROM FISH_INFO A 
      JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
      GROUP BY FISH_TYPE) B ON (A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH)) B
      ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY ID ASC;
      