-- ROOT(PARENT) -> PARENT -> CHILD
/*
A테이블에서 현재 RARE인 아이템들의 ITEM_ID를 찾는다.
찾은 ITEM_ID를 이용하여 B테이블로 접근하여 PARENT_ITEM_ID에 대입한다.
그때의 ITEM_ID를 찾은 후, ITEM_INFO 테이블에서 해당되는 값을 찾는다.

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY FROM ITEM_INFO A JOIN 
(SELECT B.ITEM_ID
FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID) B 
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC;
*/

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY I.ITEM_ID DESC;




