/*
-- 년도별 가장 큰 COLONY 값 반환
SELECT YEAR(DIFFERENTIATION_DATE), MAX(SIZE_OF_COLONY) FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
*/

SELECT YEAR, (MMAX-SIZE_OF_COLONY) AS YEAR_DEV, ID FROM ECOLI_DATA A 
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MMAX
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) B
      ON YEAR(A.DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;